#!/bin/bash

folder=$(printf $1 | grep -o -P "[^/]+\\.in$" | sed "s/\\.in$//")

../../bin/hdfs dfs -rm -r -f /user/wijayaerick/testcase/output/$folder
hadoop com.sun.tools.javac.Main TriangleCount.java
jar cf tc.jar TriangleCount*.class
hadoop jar tc.jar TriangleCount $1 /user/wijayaerick/testcase/output/$folder
