#!/bin/bash

scp -r testcase/input hduser@167.205.35.25:/home/hduser/Application/hadoop-2.7.1/user/wijayaerick/testcase
scp TriangleCount.java execute hduser@167.205.35.25:/home/hduser/Application/hadoop-2.7.1/user/wijayaerick

ssh hduser@167.205.35.25 "cd /home/hduser/Application/hadoop-2.7.1/user/wijayaerick; ./execute /user/wijayaerick/testcase/input/$1"
./get $1
